/* Generated by Yosys 0.69+190 (git sha1 0e8336b4e, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/pmc_apb_slave.v:6.1-93.10" *)
module pmc_apb_slave(PCLK, PRESETn, PADDR, PSEL, PENABLE, PWRITE, PWDATA, PREADY, PRDATA, hw_sleep_req, wake_irq, cpu_ret_save, cpu_ret_restore, cpu_iso_en, cpu_rst_n, cpu_pwr_sw_en);
  (* src = "rtl/pmc_apb_slave.v:11.34-11.38" *)
  input PCLK;
  wire PCLK;
  (* src = "rtl/pmc_apb_slave.v:12.34-12.41" *)
  input PRESETn;
  wire PRESETn;
  (* src = "rtl/pmc_apb_slave.v:13.34-13.39" *)
  input [7:0] PADDR;
  wire [7:0] PADDR;
  (* src = "rtl/pmc_apb_slave.v:14.34-14.38" *)
  input PSEL;
  wire PSEL;
  (* src = "rtl/pmc_apb_slave.v:15.34-15.41" *)
  input PENABLE;
  wire PENABLE;
  (* src = "rtl/pmc_apb_slave.v:16.34-16.40" *)
  input PWRITE;
  wire PWRITE;
  (* src = "rtl/pmc_apb_slave.v:17.34-17.40" *)
  input [31:0] PWDATA;
  wire [31:0] PWDATA;
  (* src = "rtl/pmc_apb_slave.v:18.34-18.40" *)
  output PREADY;
  wire PREADY;
  (* src = "rtl/pmc_apb_slave.v:19.34-19.40" *)
  output [31:0] PRDATA;
  wire [31:0] PRDATA;
  (* src = "rtl/pmc_apb_slave.v:22.34-22.46" *)
  input hw_sleep_req;
  wire hw_sleep_req;
  (* src = "rtl/pmc_apb_slave.v:23.34-23.42" *)
  input wake_irq;
  wire wake_irq;
  (* src = "rtl/pmc_apb_slave.v:26.34-26.46" *)
  output cpu_ret_save;
  wire cpu_ret_save;
  (* src = "rtl/pmc_apb_slave.v:27.34-27.49" *)
  output cpu_ret_restore;
  wire cpu_ret_restore;
  (* src = "rtl/pmc_apb_slave.v:28.34-28.44" *)
  output cpu_iso_en;
  wire cpu_iso_en;
  (* src = "rtl/pmc_apb_slave.v:29.34-29.43" *)
  output cpu_rst_n;
  wire cpu_rst_n;
  (* src = "rtl/pmc_apb_slave.v:30.34-30.47" *)
  output cpu_pwr_sw_en;
  wire cpu_pwr_sw_en;
  (* src = "rtl/pmc_apb_slave.v:67.5-77.8" *)
  wire [31:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire [3:0] _005_;
  wire [1:0] _006_;
  wire [3:0] _007_;
  wire [1:0] _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire [3:0] _075_;
  wire [1:0] _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  (* src = "rtl/pmc_apb_slave.v:57.22-57.37" *)
  wire _116_;
  (* src = "rtl/pmc_apb_slave.v:57.22-57.47" *)
  wire _117_;
  (* src = "rtl/pmc_apb_slave.v:69.13-69.28" *)
  wire _118_;
  (* src = "rtl/pmc_apb_slave.v:69.21-69.28" *)
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  (* src = "rtl/pmc_apb_slave.v:44.16-44.34" *)
  wire combined_sleep_req;
  (* src = "rtl/pmc_apb_slave.v:43.16-43.28" *)
  wire pmc_idle_out;
  (* src = "rtl/pmc_apb_slave.v:39.26-39.38" *)
  reg [31:0] reg_pmc_ctrl;
  (* src = "rtl/pmc_apb_slave.v:40.26-40.40" *)
  reg [31:0] reg_pmc_timing;
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[20] <= 1'h0;
    else if (_003_) reg_pmc_timing[20] <= PWDATA[20];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[21] <= 1'h0;
    else if (_003_) reg_pmc_timing[21] <= PWDATA[21];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[22] <= 1'h0;
    else if (_003_) reg_pmc_timing[22] <= PWDATA[22];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[23] <= 1'h0;
    else if (_003_) reg_pmc_timing[23] <= PWDATA[23];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[24] <= 1'h0;
    else if (_003_) reg_pmc_timing[24] <= PWDATA[24];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[25] <= 1'h0;
    else if (_003_) reg_pmc_timing[25] <= PWDATA[25];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[26] <= 1'h0;
    else if (_003_) reg_pmc_timing[26] <= PWDATA[26];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[27] <= 1'h0;
    else if (_003_) reg_pmc_timing[27] <= PWDATA[27];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[28] <= 1'h0;
    else if (_003_) reg_pmc_timing[28] <= PWDATA[28];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[29] <= 1'h0;
    else if (_003_) reg_pmc_timing[29] <= PWDATA[29];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[30] <= 1'h0;
    else if (_003_) reg_pmc_timing[30] <= PWDATA[30];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[31] <= 1'h0;
    else if (_003_) reg_pmc_timing[31] <= PWDATA[31];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[0] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[0] <= PWDATA[0];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[1] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[1] <= PWDATA[1];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[2] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[2] <= PWDATA[2];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[3] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[3] <= PWDATA[3];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[4] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[4] <= PWDATA[4];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[5] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[5] <= PWDATA[5];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[6] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[6] <= PWDATA[6];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[7] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[7] <= PWDATA[7];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[8] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[8] <= PWDATA[8];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[9] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[9] <= PWDATA[9];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[10] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[10] <= PWDATA[10];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[11] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[11] <= PWDATA[11];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[12] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[12] <= PWDATA[12];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[13] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[13] <= PWDATA[13];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[14] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[14] <= PWDATA[14];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[15] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[15] <= PWDATA[15];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[16] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[16] <= PWDATA[16];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[17] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[17] <= PWDATA[17];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[18] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[18] <= PWDATA[18];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[19] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[19] <= PWDATA[19];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[20] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[20] <= PWDATA[20];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[21] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[21] <= PWDATA[21];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[22] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[22] <= PWDATA[22];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[23] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[23] <= PWDATA[23];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[24] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[24] <= PWDATA[24];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[25] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[25] <= PWDATA[25];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[26] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[26] <= PWDATA[26];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[27] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[27] <= PWDATA[27];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[28] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[28] <= PWDATA[28];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[29] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[29] <= PWDATA[29];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[30] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[30] <= PWDATA[30];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_ctrl[31] <= 1'h0;
    else if (_004_) reg_pmc_ctrl[31] <= PWDATA[31];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[0] <= 1'h0;
    else if (_003_) reg_pmc_timing[0] <= PWDATA[0];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[1] <= 1'h0;
    else if (_003_) reg_pmc_timing[1] <= PWDATA[1];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[2] <= 1'h1;
    else if (_003_) reg_pmc_timing[2] <= PWDATA[2];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[3] <= 1'h0;
    else if (_003_) reg_pmc_timing[3] <= PWDATA[3];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[4] <= 1'h0;
    else if (_003_) reg_pmc_timing[4] <= PWDATA[4];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[5] <= 1'h0;
    else if (_003_) reg_pmc_timing[5] <= PWDATA[5];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[6] <= 1'h0;
    else if (_003_) reg_pmc_timing[6] <= PWDATA[6];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[7] <= 1'h0;
    else if (_003_) reg_pmc_timing[7] <= PWDATA[7];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[8] <= 1'h0;
    else if (_003_) reg_pmc_timing[8] <= PWDATA[8];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[9] <= 1'h0;
    else if (_003_) reg_pmc_timing[9] <= PWDATA[9];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[10] <= 1'h0;
    else if (_003_) reg_pmc_timing[10] <= PWDATA[10];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[11] <= 1'h0;
    else if (_003_) reg_pmc_timing[11] <= PWDATA[11];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[12] <= 1'h0;
    else if (_003_) reg_pmc_timing[12] <= PWDATA[12];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[13] <= 1'h0;
    else if (_003_) reg_pmc_timing[13] <= PWDATA[13];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[14] <= 1'h0;
    else if (_003_) reg_pmc_timing[14] <= PWDATA[14];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[15] <= 1'h0;
    else if (_003_) reg_pmc_timing[15] <= PWDATA[15];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[16] <= 1'h0;
    else if (_003_) reg_pmc_timing[16] <= PWDATA[16];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[17] <= 1'h0;
    else if (_003_) reg_pmc_timing[17] <= PWDATA[17];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[18] <= 1'h0;
    else if (_003_) reg_pmc_timing[18] <= PWDATA[18];
  (* src = "rtl/pmc_apb_slave.v:53.5-64.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) reg_pmc_timing[19] <= 1'h0;
    else if (_003_) reg_pmc_timing[19] <= PWDATA[19];
  assign _001_ = ~PADDR[3];
  assign _002_ = ~PADDR[2];
  assign combined_sleep_req = hw_sleep_req |(* src = "rtl/pmc_apb_slave.v:47.33-47.63" *)  reg_pmc_ctrl[0];
  assign _005_[1] = _002_ |(* src = "rtl/pmc_apb_slave.v:71.56-71.56|rtl/pmc_apb_slave.v:70.13-75.20" *)  PADDR[3];
  assign _006_[0] = _005_[0] |(* src = "rtl/pmc_apb_slave.v:71.56-71.56|rtl/pmc_apb_slave.v:70.13-75.20" *)  _005_[1];
  assign _006_[1] = _005_[2] |(* src = "rtl/pmc_apb_slave.v:71.56-71.56|rtl/pmc_apb_slave.v:70.13-75.20" *)  _005_[3];
  assign _078_ = _006_[0] |(* src = "rtl/pmc_apb_slave.v:71.56-71.56|rtl/pmc_apb_slave.v:70.13-75.20" *)  _006_[1];
  assign _007_[1] = PADDR[2] |(* src = "rtl/pmc_apb_slave.v:59.59-59.59|rtl/pmc_apb_slave.v:58.13-62.20" *)  _001_;
  assign _008_[0] = _005_[0] |(* src = "rtl/pmc_apb_slave.v:59.59-59.59|rtl/pmc_apb_slave.v:58.13-62.20" *)  _007_[1];
  assign _079_ = _008_[0] |(* src = "rtl/pmc_apb_slave.v:59.59-59.59|rtl/pmc_apb_slave.v:58.13-62.20" *)  _006_[1];
  assign _004_ = _117_ & _122_;
  assign _003_ = _117_ & _120_;
  assign _009_ = _120_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _121_;
  assign _010_ = _009_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _011_ = _080_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _081_;
  assign _012_ = _011_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _082_;
  assign _014_ = _013_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _083_;
  assign _016_ = _015_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _084_;
  assign _018_ = _017_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _085_;
  assign _019_ = _086_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _087_;
  assign _020_ = _019_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _088_;
  assign _022_ = _021_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _089_;
  assign _024_ = _023_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _090_;
  assign _026_ = _025_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _091_;
  assign _028_ = _027_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _092_;
  assign _030_ = _029_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _093_;
  assign _032_ = _031_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _094_;
  assign _034_ = _033_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _095_;
  assign _036_ = _035_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _096_;
  assign _038_ = _037_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _097_;
  assign _040_ = _039_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _098_;
  assign _042_ = _041_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _099_;
  assign _044_ = _043_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _100_;
  assign _046_ = _045_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _101_;
  assign _048_ = _047_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _102_;
  assign _050_ = _049_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _103_;
  assign _052_ = _051_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _104_;
  assign _054_ = _053_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _105_;
  assign _056_ = _055_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _106_;
  assign _058_ = _057_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _107_;
  assign _060_ = _059_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _108_;
  assign _062_ = _061_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _109_;
  assign _064_ = _063_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _110_;
  assign _066_ = _065_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _111_;
  assign _068_ = _067_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _112_;
  assign _070_ = _069_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _113_;
  assign _072_ = _071_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _114_;
  assign _074_ = _073_ |(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _115_;
  assign _005_[0] = PADDR[0] |(* src = "rtl/pmc_apb_slave.v:58.25-58.25|rtl/pmc_apb_slave.v:58.13-62.20" *)  PADDR[1];
  assign _075_[1] = PADDR[2] |(* src = "rtl/pmc_apb_slave.v:58.25-58.25|rtl/pmc_apb_slave.v:58.13-62.20" *)  PADDR[3];
  assign _005_[2] = PADDR[4] |(* src = "rtl/pmc_apb_slave.v:58.25-58.25|rtl/pmc_apb_slave.v:58.13-62.20" *)  PADDR[5];
  assign _005_[3] = PADDR[6] |(* src = "rtl/pmc_apb_slave.v:58.25-58.25|rtl/pmc_apb_slave.v:58.13-62.20" *)  PADDR[7];
  assign _076_[0] = _005_[0] |(* src = "rtl/pmc_apb_slave.v:58.25-58.25|rtl/pmc_apb_slave.v:58.13-62.20" *)  _075_[1];
  assign _077_ = _076_[0] |(* src = "rtl/pmc_apb_slave.v:58.25-58.25|rtl/pmc_apb_slave.v:58.13-62.20" *)  _006_[1];
  assign _119_ = ~(* src = "rtl/pmc_apb_slave.v:69.21-69.28" *) PWRITE;
  assign _121_ = ~(* src = "rtl/pmc_apb_slave.v:71.56-71.56|rtl/pmc_apb_slave.v:70.13-75.20" *) _078_;
  assign _120_ = ~(* src = "rtl/pmc_apb_slave.v:59.59-59.59|rtl/pmc_apb_slave.v:58.13-62.20" *) _079_;
  assign _122_ = ~(* src = "rtl/pmc_apb_slave.v:58.25-58.25|rtl/pmc_apb_slave.v:58.13-62.20" *) _077_;
  assign _116_ = PSEL &(* src = "rtl/pmc_apb_slave.v:57.22-57.37" *)  PENABLE;
  assign _117_ = _116_ &(* src = "rtl/pmc_apb_slave.v:57.22-57.47" *)  PWRITE;
  assign _118_ = PSEL &(* src = "rtl/pmc_apb_slave.v:69.13-69.28" *)  _119_;
  assign PRDATA[0] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[0] : 1'h0;
  assign PRDATA[1] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[1] : 1'h0;
  assign PRDATA[2] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[2] : 1'h0;
  assign PRDATA[3] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[3] : 1'h0;
  assign PRDATA[4] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[4] : 1'h0;
  assign PRDATA[5] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[5] : 1'h0;
  assign PRDATA[6] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[6] : 1'h0;
  assign PRDATA[7] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[7] : 1'h0;
  assign PRDATA[8] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[8] : 1'h0;
  assign PRDATA[9] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[9] : 1'h0;
  assign PRDATA[10] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[10] : 1'h0;
  assign PRDATA[11] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[11] : 1'h0;
  assign PRDATA[12] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[12] : 1'h0;
  assign PRDATA[13] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[13] : 1'h0;
  assign PRDATA[14] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[14] : 1'h0;
  assign PRDATA[15] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[15] : 1'h0;
  assign PRDATA[16] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[16] : 1'h0;
  assign PRDATA[17] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[17] : 1'h0;
  assign PRDATA[18] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[18] : 1'h0;
  assign PRDATA[19] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[19] : 1'h0;
  assign PRDATA[20] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[20] : 1'h0;
  assign PRDATA[21] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[21] : 1'h0;
  assign PRDATA[22] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[22] : 1'h0;
  assign PRDATA[23] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[23] : 1'h0;
  assign PRDATA[24] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[24] : 1'h0;
  assign PRDATA[25] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[25] : 1'h0;
  assign PRDATA[26] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[26] : 1'h0;
  assign PRDATA[27] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[27] : 1'h0;
  assign PRDATA[28] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[28] : 1'h0;
  assign PRDATA[29] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[29] : 1'h0;
  assign PRDATA[30] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[30] : 1'h0;
  assign PRDATA[31] = _118_ ? (* src = "rtl/pmc_apb_slave.v:69.13-69.28|rtl/pmc_apb_slave.v:69.9-76.12" *) _000_[31] : 1'h0;
  assign _080_ = reg_pmc_timing[0] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _081_ = pmc_idle_out &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _121_;
  assign _082_ = reg_pmc_ctrl[0] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _013_ = reg_pmc_timing[1] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _083_ = reg_pmc_ctrl[1] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _015_ = reg_pmc_timing[2] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _084_ = reg_pmc_ctrl[2] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _017_ = reg_pmc_timing[3] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _085_ = reg_pmc_ctrl[3] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _086_ = reg_pmc_timing[4] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _087_ = cpu_pwr_sw_en &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _121_;
  assign _088_ = reg_pmc_ctrl[4] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _021_ = reg_pmc_timing[5] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _089_ = reg_pmc_ctrl[5] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _023_ = reg_pmc_timing[6] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _090_ = reg_pmc_ctrl[6] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _025_ = reg_pmc_timing[7] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _091_ = reg_pmc_ctrl[7] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _027_ = reg_pmc_timing[8] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _092_ = reg_pmc_ctrl[8] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _029_ = reg_pmc_timing[9] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _093_ = reg_pmc_ctrl[9] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _031_ = reg_pmc_timing[10] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _094_ = reg_pmc_ctrl[10] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _033_ = reg_pmc_timing[11] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _095_ = reg_pmc_ctrl[11] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _035_ = reg_pmc_timing[12] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _096_ = reg_pmc_ctrl[12] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _037_ = reg_pmc_timing[13] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _097_ = reg_pmc_ctrl[13] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _039_ = reg_pmc_timing[14] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _098_ = reg_pmc_ctrl[14] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _041_ = reg_pmc_timing[15] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _099_ = reg_pmc_ctrl[15] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _043_ = reg_pmc_timing[16] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _100_ = reg_pmc_ctrl[16] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _045_ = reg_pmc_timing[17] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _101_ = reg_pmc_ctrl[17] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _047_ = reg_pmc_timing[18] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _102_ = reg_pmc_ctrl[18] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _049_ = reg_pmc_timing[19] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _103_ = reg_pmc_ctrl[19] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _051_ = reg_pmc_timing[20] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _104_ = reg_pmc_ctrl[20] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _053_ = reg_pmc_timing[21] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _105_ = reg_pmc_ctrl[21] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _055_ = reg_pmc_timing[22] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _106_ = reg_pmc_ctrl[22] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _057_ = reg_pmc_timing[23] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _107_ = reg_pmc_ctrl[23] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _059_ = reg_pmc_timing[24] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _108_ = reg_pmc_ctrl[24] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _061_ = reg_pmc_timing[25] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _109_ = reg_pmc_ctrl[25] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _063_ = reg_pmc_timing[26] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _110_ = reg_pmc_ctrl[26] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _065_ = reg_pmc_timing[27] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _111_ = reg_pmc_ctrl[27] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _067_ = reg_pmc_timing[28] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _112_ = reg_pmc_ctrl[28] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _069_ = reg_pmc_timing[29] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _113_ = reg_pmc_ctrl[29] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _071_ = reg_pmc_timing[30] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _114_ = reg_pmc_ctrl[30] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _073_ = reg_pmc_timing[31] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _120_;
  assign _115_ = reg_pmc_ctrl[31] &(* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *)  _122_;
  assign _000_[0] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _012_ : 1'h0;
  assign _000_[1] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _014_ : 1'h0;
  assign _000_[2] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _016_ : 1'h0;
  assign _000_[3] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _018_ : 1'h0;
  assign _000_[4] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _020_ : 1'h0;
  assign _000_[5] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _022_ : 1'h0;
  assign _000_[6] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _024_ : 1'h0;
  assign _000_[7] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _026_ : 1'h0;
  assign _000_[8] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _028_ : 1'h0;
  assign _000_[9] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _030_ : 1'h0;
  assign _000_[10] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _032_ : 1'h0;
  assign _000_[11] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _034_ : 1'h0;
  assign _000_[12] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _036_ : 1'h0;
  assign _000_[13] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _038_ : 1'h0;
  assign _000_[14] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _040_ : 1'h0;
  assign _000_[15] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _042_ : 1'h0;
  assign _000_[16] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _044_ : 1'h0;
  assign _000_[17] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _046_ : 1'h0;
  assign _000_[18] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _048_ : 1'h0;
  assign _000_[19] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _050_ : 1'h0;
  assign _000_[20] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _052_ : 1'h0;
  assign _000_[21] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _054_ : 1'h0;
  assign _000_[22] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _056_ : 1'h0;
  assign _000_[23] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _058_ : 1'h0;
  assign _000_[24] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _060_ : 1'h0;
  assign _000_[25] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _062_ : 1'h0;
  assign _000_[26] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _064_ : 1'h0;
  assign _000_[27] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _066_ : 1'h0;
  assign _000_[28] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _068_ : 1'h0;
  assign _000_[29] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _070_ : 1'h0;
  assign _000_[30] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _072_ : 1'h0;
  assign _000_[31] = _010_ ? (* src = "rtl/pmc_apb_slave.v:72.88-72.88|rtl/pmc_apb_slave.v:70.13-75.20" *) _074_ : 1'h0;
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/pmc_apb_slave.v:80.14-91.6" *)
  pmc_core u_pmc_core (
    .clk_aon(PCLK),
    .cpu_iso_en(cpu_iso_en),
    .cpu_pwr_sw_en(cpu_pwr_sw_en),
    .cpu_ret_restore(cpu_ret_restore),
    .cpu_ret_save(cpu_ret_save),
    .cpu_rst_n(cpu_rst_n),
    .pmc_idle(pmc_idle_out),
    .rst_n_aon(PRESETn),
    .sleep_req(combined_sleep_req),
    .wake_irq(wake_irq)
  );
  assign { _007_[3:2], _007_[0] } = { _005_[3:2], _005_[0] };
  assign _008_[1] = _006_[1];
  assign { _075_[3:2], _075_[0] } = { _005_[3:2], _005_[0] };
  assign _076_[1] = _006_[1];
  assign PREADY = 1'h1;
endmodule

(* src = "rtl/pmc_core.v:7.1-207.10" *)
module pmc_core(clk_aon, rst_n_aon, sleep_req, wake_irq, pmc_idle, cpu_ret_save, cpu_ret_restore, cpu_iso_en, cpu_rst_n, cpu_pwr_sw_en);
  (* src = "rtl/pmc_core.v:10.17-10.24" *)
  input clk_aon;
  wire clk_aon;
  (* src = "rtl/pmc_core.v:11.17-11.26" *)
  input rst_n_aon;
  wire rst_n_aon;
  (* src = "rtl/pmc_core.v:14.17-14.26" *)
  input sleep_req;
  wire sleep_req;
  (* src = "rtl/pmc_core.v:15.17-15.25" *)
  input wake_irq;
  wire wake_irq;
  (* src = "rtl/pmc_core.v:16.17-16.25" *)
  output pmc_idle;
  wire pmc_idle;
  (* src = "rtl/pmc_core.v:19.17-19.29" *)
  output cpu_ret_save;
  wire cpu_ret_save;
  (* src = "rtl/pmc_core.v:20.17-20.32" *)
  output cpu_ret_restore;
  wire cpu_ret_restore;
  (* src = "rtl/pmc_core.v:21.17-21.27" *)
  output cpu_iso_en;
  wire cpu_iso_en;
  (* src = "rtl/pmc_core.v:22.17-22.26" *)
  output cpu_rst_n;
  wire cpu_rst_n;
  (* src = "rtl/pmc_core.v:23.17-23.30" *)
  output cpu_pwr_sw_en;
  wire cpu_pwr_sw_en;
  (* src = "rtl/pmc_core.v:47.5-58.8" *)
  wire [3:0] _000_;
  (* src = "rtl/pmc_core.v:63.5-140.8" *)
  wire [3:0] _001_;
  (* src = "rtl/pmc_core.v:63.5-140.8" *)
  wire _002_;
  (* src = "rtl/pmc_core.v:63.5-140.8" *)
  wire [3:0] _003_;
  (* src = "rtl/pmc_core.v:63.5-140.8" *)
  wire [3:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire [3:0] _032_;
  wire [1:0] _033_;
  wire [4:0] _034_;
  wire [1:0] _035_;
  wire _036_;
  wire [1:0] _037_;
  wire [1:0] _038_;
  wire [1:0] _039_;
  wire [1:0] _040_;
  wire [1:0] _041_;
  wire [1:0] _042_;
  wire [1:0] _043_;
  wire [1:0] _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire [4:0] _049_;
  wire [1:0] _050_;
  wire _051_;
  wire _052_;
  wire [4:0] _053_;
  wire [1:0] _054_;
  wire _055_;
  wire _056_;
  wire [4:0] _057_;
  wire [1:0] _058_;
  wire _059_;
  wire _060_;
  wire [4:0] _061_;
  wire [1:0] _062_;
  wire _063_;
  wire _064_;
  wire [4:0] _065_;
  wire [1:0] _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/pmc_core.v:56.26-56.38|C:\\oss-cad-suite\\bin\\../share/yosys/techmap.v:274.23-274.25" *)
  wire [3:0] _102_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/pmc_core.v:56.26-56.38|C:\\oss-cad-suite\\bin\\../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _103_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/pmc_core.v:56.26-56.38|C:\\oss-cad-suite\\bin\\../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _104_;
  (* src = "rtl/pmc_core.v:38.15-38.28" *)
  reg [3:0] current_state;
  (* src = "rtl/pmc_core.v:38.30-38.40" *)
  wire [3:0] next_state;
  (* src = "rtl/pmc_core.v:41.15-41.20" *)
  reg [3:0] timer;
  (* src = "rtl/pmc_core.v:42.15-42.26" *)
  wire timer_clear;
  (* full_case = 32'd1 *)
  (* src = "rtl/pmc_core.v:154.9-204.16" *)
  reg [5:0] \$auto$proc_rom.cc:155:do_switch$23  [15:0];
  initial begin
    \$auto$proc_rom.cc:155:do_switch$23 [0] = 6'h30;
    \$auto$proc_rom.cc:155:do_switch$23 [1] = 6'h32;
    \$auto$proc_rom.cc:155:do_switch$23 [2] = 6'h28;
    \$auto$proc_rom.cc:155:do_switch$23 [3] = 6'h38;
    \$auto$proc_rom.cc:155:do_switch$23 [4] = 6'h20;
    \$auto$proc_rom.cc:155:do_switch$23 [5] = 6'h28;
    \$auto$proc_rom.cc:155:do_switch$23 [6] = 6'h08;
    \$auto$proc_rom.cc:155:do_switch$23 [7] = 6'h09;
    \$auto$proc_rom.cc:155:do_switch$23 [8] = 6'h30;
    \$auto$proc_rom.cc:155:do_switch$23 [9] = 6'h30;
    \$auto$proc_rom.cc:155:do_switch$23 [10] = 6'h30;
    \$auto$proc_rom.cc:155:do_switch$23 [11] = 6'h30;
    \$auto$proc_rom.cc:155:do_switch$23 [12] = 6'h24;
    \$auto$proc_rom.cc:155:do_switch$23 [13] = 6'h30;
    \$auto$proc_rom.cc:155:do_switch$23 [14] = 6'h30;
    \$auto$proc_rom.cc:155:do_switch$23 [15] = 6'h30;
  end
  assign { cpu_pwr_sw_en, cpu_rst_n, cpu_iso_en, cpu_ret_restore, cpu_ret_save, pmc_idle } = \$auto$proc_rom.cc:155:do_switch$23 [current_state];
  (* src = "rtl/pmc_core.v:47.5-58.8" *)
  always @(posedge clk_aon, negedge rst_n_aon)
    if (!rst_n_aon) current_state[0] <= 1'h0;
    else if (_031_) current_state[0] <= next_state[0];
  (* src = "rtl/pmc_core.v:47.5-58.8" *)
  always @(posedge clk_aon, negedge rst_n_aon)
    if (!rst_n_aon) current_state[1] <= 1'h0;
    else if (_031_) current_state[1] <= next_state[1];
  (* src = "rtl/pmc_core.v:47.5-58.8" *)
  always @(posedge clk_aon, negedge rst_n_aon)
    if (!rst_n_aon) current_state[2] <= 1'h0;
    else if (_031_) current_state[2] <= next_state[2];
  (* src = "rtl/pmc_core.v:47.5-58.8" *)
  always @(posedge clk_aon, negedge rst_n_aon)
    if (!rst_n_aon) current_state[3] <= 1'h0;
    else if (_031_) current_state[3] <= next_state[3];
  (* src = "rtl/pmc_core.v:47.5-58.8" *)
  always @(posedge clk_aon, negedge rst_n_aon)
    if (!rst_n_aon) timer[0] <= 1'h0;
    else timer[0] <= _000_[0];
  (* src = "rtl/pmc_core.v:47.5-58.8" *)
  always @(posedge clk_aon, negedge rst_n_aon)
    if (!rst_n_aon) timer[1] <= 1'h0;
    else timer[1] <= _000_[1];
  (* src = "rtl/pmc_core.v:47.5-58.8" *)
  always @(posedge clk_aon, negedge rst_n_aon)
    if (!rst_n_aon) timer[2] <= 1'h0;
    else timer[2] <= _000_[2];
  (* src = "rtl/pmc_core.v:47.5-58.8" *)
  always @(posedge clk_aon, negedge rst_n_aon)
    if (!rst_n_aon) timer[3] <= 1'h0;
    else timer[3] <= _000_[3];
  assign _103_[0] = ~timer[0];
  assign _006_ = ~current_state[2];
  assign _007_ = ~current_state[1];
  assign _008_ = ~current_state[0];
  assign _010_ = ~current_state[3];
  assign _104_[1] = timer[1] ^(* src = "rtl/pmc_core.v:56.26-56.38|C:\\oss-cad-suite\\bin\\../share/yosys/techmap.v:296.13-296.25" *)  timer[0];
  assign _104_[2] = timer[2] ^(* src = "rtl/pmc_core.v:56.26-56.38|C:\\oss-cad-suite\\bin\\../share/yosys/techmap.v:296.13-296.25" *)  _102_[1];
  assign _104_[3] = timer[3] ^(* src = "rtl/pmc_core.v:56.26-56.38|C:\\oss-cad-suite\\bin\\../share/yosys/techmap.v:296.13-296.25" *)  _102_[2];
  assign _102_[2] = timer[2] &(* src = "rtl/pmc_core.v:56.26-56.38|C:\\oss-cad-suite\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\oss-cad-suite\\bin\\../share/yosys/techmap.v:248.19-248.41" *)  _102_[1];
  assign _102_[1] = timer[1] &(* src = "rtl/pmc_core.v:56.26-56.38|C:\\oss-cad-suite\\bin\\../share/yosys/techmap.v:293.27-293.63|C:\\oss-cad-suite\\bin\\../share/yosys/techmap.v:240.19-240.41" *)  timer[0];
  assign _032_[0] = _092_ | _094_;
  assign _032_[2] = _097_ | _099_;
  assign _032_[3] = _100_ | _101_;
  assign _033_[0] = _032_[0] | _032_[1];
  assign _033_[1] = _032_[2] | _032_[3];
  assign _005_ = _033_[0] | _033_[1];
  assign _034_[0] = _030_ & _029_;
  assign _034_[1] = _028_ & _027_;
  assign _034_[2] = _026_ & _025_;
  assign _034_[3] = _024_ & _023_;
  assign _034_[4] = _022_ & _021_;
  assign _035_[0] = _034_[0] & _034_[1];
  assign _035_[1] = _034_[2] & _034_[3];
  assign _036_ = _035_[0] & _035_[1];
  assign _031_ = _036_ & _034_[4];
  assign _030_ = _002_ | _020_;
  assign _029_ = _002_ | _019_;
  assign _028_ = _002_ | _018_;
  assign _027_ = _002_ | _017_;
  assign _026_ = _002_ | _016_;
  assign _025_ = _002_ | _015_;
  assign _024_ = _002_ | _014_;
  assign _023_ = _002_ | _013_;
  assign _022_ = wake_irq | _012_;
  assign _021_ = sleep_req | _011_;
  assign _037_[0] = timer[0] |(* src = "rtl/pmc_core.v:132.21-132.44" *)  timer[1];
  assign _037_[1] = _009_ |(* src = "rtl/pmc_core.v:132.21-132.44" *)  timer[3];
  assign _069_ = _037_[0] |(* src = "rtl/pmc_core.v:132.21-132.44" *)  _037_[1];
  assign _038_[1] = current_state[2] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _010_;
  assign _013_ = _038_[0] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _038_[1];
  assign _039_[1] = _006_ |(* src = "rtl/pmc_core.v:122.16-122.16|rtl/pmc_core.v:67.9-139.16" *)  _010_;
  assign _014_ = _038_[0] |(* src = "rtl/pmc_core.v:122.16-122.16|rtl/pmc_core.v:67.9-139.16" *)  _039_[1];
  assign _038_[0] = current_state[0] |(* src = "rtl/pmc_core.v:115.16-115.16|rtl/pmc_core.v:67.9-139.16" *)  current_state[1];
  assign _015_ = _038_[0] |(* src = "rtl/pmc_core.v:115.16-115.16|rtl/pmc_core.v:67.9-139.16" *)  _040_[1];
  assign _041_[0] = _008_ |(* src = "rtl/pmc_core.v:108.16-108.16|rtl/pmc_core.v:67.9-139.16" *)  current_state[1];
  assign _040_[1] = _006_ |(* src = "rtl/pmc_core.v:108.16-108.16|rtl/pmc_core.v:67.9-139.16" *)  current_state[3];
  assign _016_ = _041_[0] |(* src = "rtl/pmc_core.v:108.16-108.16|rtl/pmc_core.v:67.9-139.16" *)  _040_[1];
  assign _042_[0] = _008_ |(* src = "rtl/pmc_core.v:101.16-101.16|rtl/pmc_core.v:67.9-139.16" *)  _007_;
  assign _012_ = _042_[0] |(* src = "rtl/pmc_core.v:101.16-101.16|rtl/pmc_core.v:67.9-139.16" *)  _040_[1];
  assign _043_[0] = current_state[0] |(* src = "rtl/pmc_core.v:94.16-94.16|rtl/pmc_core.v:67.9-139.16" *)  _007_;
  assign _017_ = _043_[0] |(* src = "rtl/pmc_core.v:94.16-94.16|rtl/pmc_core.v:67.9-139.16" *)  _040_[1];
  assign _018_ = _043_[0] |(* src = "rtl/pmc_core.v:87.16-87.16|rtl/pmc_core.v:67.9-139.16" *)  _044_[1];
  assign _044_[1] = current_state[2] |(* src = "rtl/pmc_core.v:80.16-80.16|rtl/pmc_core.v:67.9-139.16" *)  current_state[3];
  assign _019_ = _042_[0] |(* src = "rtl/pmc_core.v:80.16-80.16|rtl/pmc_core.v:67.9-139.16" *)  _044_[1];
  assign _020_ = _041_[0] |(* src = "rtl/pmc_core.v:73.16-73.16|rtl/pmc_core.v:67.9-139.16" *)  _044_[1];
  assign _045_ = _098_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _093_;
  assign _046_ = _045_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _005_;
  assign _047_ = _070_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _071_;
  assign _048_ = _047_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _072_;
  assign _049_[0] = _099_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _100_;
  assign _049_[1] = _101_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _092_;
  assign _049_[2] = _093_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _094_;
  assign _032_[1] = _095_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _096_;
  assign _049_[4] = _097_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _098_;
  assign _050_[0] = _049_[0] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _049_[1];
  assign _050_[1] = _049_[2] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _032_[1];
  assign _051_ = _050_[0] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _050_[1];
  assign _052_ = _051_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _049_[4];
  assign _053_[1] = _075_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _076_;
  assign _053_[3] = _079_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _080_;
  assign _053_[4] = _081_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _082_;
  assign _054_[0] = _053_[0] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _053_[1];
  assign _054_[1] = _053_[2] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _053_[3];
  assign _055_ = _054_[0] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _054_[1];
  assign _056_ = _055_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _053_[4];
  assign _057_[2] = _083_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _078_;
  assign _057_[3] = _084_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _085_;
  assign _057_[4] = _081_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _086_;
  assign _058_[1] = _057_[2] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _057_[3];
  assign _059_ = _054_[0] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _058_[1];
  assign _060_ = _059_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _057_[4];
  assign _053_[0] = _073_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _074_;
  assign _061_[1] = _087_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _088_;
  assign _053_[2] = _077_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _078_;
  assign _061_[3] = _084_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _080_;
  assign _062_[0] = _053_[0] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _061_[1];
  assign _062_[1] = _053_[2] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _061_[3];
  assign _063_ = _062_[0] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _062_[1];
  assign _064_ = _063_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _061_[4];
  assign _065_[0] = _073_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _090_;
  assign _065_[1] = _087_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _076_;
  assign _065_[2] = _083_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _091_;
  assign _061_[4] = _089_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _086_;
  assign _066_[0] = _065_[0] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _065_[1];
  assign _066_[1] = _065_[2] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _053_[3];
  assign _067_ = _066_[0] |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _066_[1];
  assign _068_ = _067_ |(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _061_[4];
  assign _011_ = _038_[0] |(* src = "rtl/pmc_core.v:67.29-67.29|rtl/pmc_core.v:67.9-139.16" *)  _044_[1];
  assign _099_ = ~(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *) _013_;
  assign _100_ = ~(* src = "rtl/pmc_core.v:122.16-122.16|rtl/pmc_core.v:67.9-139.16" *) _014_;
  assign _101_ = ~(* src = "rtl/pmc_core.v:115.16-115.16|rtl/pmc_core.v:67.9-139.16" *) _015_;
  assign _092_ = ~(* src = "rtl/pmc_core.v:108.16-108.16|rtl/pmc_core.v:67.9-139.16" *) _016_;
  assign _093_ = ~(* src = "rtl/pmc_core.v:101.16-101.16|rtl/pmc_core.v:67.9-139.16" *) _012_;
  assign _094_ = ~(* src = "rtl/pmc_core.v:94.16-94.16|rtl/pmc_core.v:67.9-139.16" *) _017_;
  assign _095_ = ~(* src = "rtl/pmc_core.v:87.16-87.16|rtl/pmc_core.v:67.9-139.16" *) _018_;
  assign _096_ = ~(* src = "rtl/pmc_core.v:80.16-80.16|rtl/pmc_core.v:67.9-139.16" *) _019_;
  assign _097_ = ~(* src = "rtl/pmc_core.v:73.16-73.16|rtl/pmc_core.v:67.9-139.16" *) _020_;
  assign _098_ = ~(* src = "rtl/pmc_core.v:67.29-67.29|rtl/pmc_core.v:67.9-139.16" *) _011_;
  assign _002_ = ~(* src = "rtl/pmc_core.v:111.21-111.44|rtl/pmc_core.v:111.17-114.20" *) _069_;
  assign _004_[1] = wake_irq ? (* src = "rtl/pmc_core.v:104.21-104.29|rtl/pmc_core.v:104.17-107.20" *) 1'h0 : 1'hx;
  assign _004_[0] = wake_irq ? (* src = "rtl/pmc_core.v:104.21-104.29|rtl/pmc_core.v:104.17-107.20" *) 1'h1 : 1'hx;
  assign _001_[3] = _069_ ? (* src = "rtl/pmc_core.v:76.21-76.44|rtl/pmc_core.v:76.17-79.20" *) 1'hx : 1'h1;
  assign _001_[0] = _069_ ? (* src = "rtl/pmc_core.v:76.21-76.44|rtl/pmc_core.v:76.17-79.20" *) 1'hx : 1'h0;
  assign _003_[0] = sleep_req ? (* src = "rtl/pmc_core.v:69.21-69.30|rtl/pmc_core.v:69.17-72.20" *) 1'h1 : 1'hx;
  assign _003_[1] = sleep_req ? (* src = "rtl/pmc_core.v:69.21-69.30|rtl/pmc_core.v:69.17-72.20" *) 1'h0 : 1'hx;
  assign _000_[0] = timer_clear ? (* src = "rtl/pmc_core.v:53.17-53.28|rtl/pmc_core.v:53.13-56.39" *) 1'h0 : _103_[0];
  assign _000_[1] = timer_clear ? (* src = "rtl/pmc_core.v:53.17-53.28|rtl/pmc_core.v:53.13-56.39" *) 1'h0 : _104_[1];
  assign _000_[2] = timer_clear ? (* src = "rtl/pmc_core.v:53.17-53.28|rtl/pmc_core.v:53.13-56.39" *) 1'h0 : _104_[2];
  assign _000_[3] = timer_clear ? (* src = "rtl/pmc_core.v:53.17-53.28|rtl/pmc_core.v:53.13-56.39" *) 1'h0 : _104_[3];
  assign _070_ = sleep_req &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _098_;
  assign _071_ = wake_irq &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _093_;
  assign _072_ = _002_ &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _005_;
  assign _079_ = _001_[0] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _095_;
  assign _082_ = _003_[0] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _098_;
  assign _075_ = _001_[0] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _101_;
  assign _076_ = _001_[0] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _092_;
  assign _083_ = _004_[1] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _093_;
  assign _085_ = _001_[3] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _096_;
  assign _081_ = _001_[3] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _097_;
  assign _073_ = _001_[0] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _099_;
  assign _074_ = _001_[0] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _100_;
  assign _087_ = _001_[3] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _101_;
  assign _088_ = _001_[3] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _092_;
  assign _077_ = _004_[0] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _093_;
  assign _078_ = _001_[3] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _094_;
  assign _084_ = _001_[3] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _095_;
  assign _080_ = _001_[0] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _096_;
  assign _089_ = _001_[0] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _097_;
  assign _086_ = _003_[1] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _098_;
  assign _090_ = _001_[3] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _100_;
  assign _091_ = _001_[0] &(* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *)  _094_;
  assign _009_ = ~(* src = "rtl/pmc_core.v:56.26-56.38|C:\\oss-cad-suite\\bin\\../share/yosys/techmap.v:279.31-279.37" *) timer[2];
  assign timer_clear = _046_ ? (* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *) _048_ : 1'h0;
  assign next_state[0] = _052_ ? (* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *) _056_ : 1'h0;
  assign next_state[1] = _052_ ? (* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *) _060_ : 1'h0;
  assign next_state[2] = _052_ ? (* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *) _064_ : 1'h0;
  assign next_state[3] = _052_ ? (* src = "rtl/pmc_core.v:129.16-129.16|rtl/pmc_core.v:67.9-139.16" *) _068_ : 1'h0;
  assign _043_[1] = _040_[1];
  assign _039_[0] = _038_[0];
  assign _049_[3] = _032_[1];
  assign _044_[0] = _043_[0];
  assign { _061_[2], _061_[0] } = { _053_[2], _053_[0] };
  assign _042_[1] = _040_[1];
  assign _065_[4:3] = { _061_[4], _053_[3] };
  assign _040_[0] = _038_[0];
  assign _102_[0] = timer[0];
  assign _058_[0] = _054_[0];
  assign _057_[1:0] = _053_[1:0];
  assign _041_[1] = _040_[1];
  assign _103_[3:1] = timer[3:1];
  assign _104_[0] = _103_[0];
  assign _001_[2:1] = { _001_[0], _001_[0] };
  assign _004_[3:2] = _004_[1:0];
  assign _003_[3:2] = { _003_[1], _003_[1] };
endmodule
