/* Generated by Yosys 0.69+190 (git sha1 0e8336b4e, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

module pmc_apb_slave(PCLK, PRESETn, PADDR, PSEL, PENABLE, PWRITE, PWDATA, PREADY, PRDATA, hw_sleep_req, wake_irq, cpu_ret_save, cpu_ret_restore, cpu_iso_en, cpu_rst_n, cpu_pwr_sw_en);
  input PCLK;
  wire PCLK;
  input PRESETn;
  wire PRESETn;
  input [7:0] PADDR;
  wire [7:0] PADDR;
  input PSEL;
  wire PSEL;
  input PENABLE;
  wire PENABLE;
  input PWRITE;
  wire PWRITE;
  input [31:0] PWDATA;
  wire [31:0] PWDATA;
  output PREADY;
  wire PREADY;
  output [31:0] PRDATA;
  wire [31:0] PRDATA;
  input hw_sleep_req;
  wire hw_sleep_req;
  input wake_irq;
  wire wake_irq;
  output cpu_ret_save;
  wire cpu_ret_save;
  output cpu_ret_restore;
  wire cpu_ret_restore;
  output cpu_iso_en;
  wire cpu_iso_en;
  output cpu_rst_n;
  wire cpu_rst_n;
  output cpu_pwr_sw_en;
  wire cpu_pwr_sw_en;
  wire [31:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire combined_sleep_req;
  wire pmc_idle_out;
  wire [31:0] reg_pmc_ctrl;
  wire [31:0] reg_pmc_timing;
  \$_NOT_  _124_ (
    .A(PWRITE),
    .Y(_043_)
  );
  \$_AND_  _125_ (
    .A(PWRITE),
    .B(PSEL),
    .Y(_044_)
  );
  \$_AND_  _126_ (
    .A(reg_pmc_ctrl[2]),
    .B(_047_),
    .Y(_013_)
  );
  \$_AND_  _127_ (
    .A(reg_pmc_ctrl[3]),
    .B(_047_),
    .Y(_014_)
  );
  \$_AND_  _128_ (
    .A(reg_pmc_ctrl[5]),
    .B(_047_),
    .Y(_016_)
  );
  \$_AND_  _129_ (
    .A(reg_pmc_ctrl[6]),
    .B(_047_),
    .Y(_017_)
  );
  \$_AND_  _130_ (
    .A(reg_pmc_ctrl[7]),
    .B(_047_),
    .Y(_018_)
  );
  \$_AND_  _131_ (
    .A(reg_pmc_ctrl[8]),
    .B(_047_),
    .Y(_019_)
  );
  \$_AND_  _132_ (
    .A(reg_pmc_ctrl[9]),
    .B(_047_),
    .Y(_020_)
  );
  \$_AND_  _133_ (
    .A(reg_pmc_ctrl[10]),
    .B(_047_),
    .Y(_021_)
  );
  \$_AND_  _134_ (
    .A(reg_pmc_ctrl[11]),
    .B(_047_),
    .Y(_022_)
  );
  \$_AND_  _135_ (
    .A(reg_pmc_ctrl[12]),
    .B(_047_),
    .Y(_023_)
  );
  \$_AND_  _136_ (
    .A(PENABLE),
    .B(_044_),
    .Y(_042_)
  );
  \$_AND_  _137_ (
    .A(reg_pmc_ctrl[13]),
    .B(_047_),
    .Y(_024_)
  );
  \$_AND_  _138_ (
    .A(reg_pmc_ctrl[14]),
    .B(_047_),
    .Y(_025_)
  );
  \$_AND_  _139_ (
    .A(reg_pmc_ctrl[15]),
    .B(_047_),
    .Y(_026_)
  );
  \$_AND_  _140_ (
    .A(reg_pmc_ctrl[16]),
    .B(_047_),
    .Y(_027_)
  );
  \$_AND_  _141_ (
    .A(reg_pmc_ctrl[17]),
    .B(_047_),
    .Y(_028_)
  );
  \$_AND_  _142_ (
    .A(reg_pmc_ctrl[18]),
    .B(_047_),
    .Y(_029_)
  );
  \$_AND_  _143_ (
    .A(reg_pmc_ctrl[19]),
    .B(_047_),
    .Y(_030_)
  );
  \$_AND_  _144_ (
    .A(reg_pmc_ctrl[20]),
    .B(_047_),
    .Y(_031_)
  );
  \$_AND_  _145_ (
    .A(reg_pmc_ctrl[21]),
    .B(_047_),
    .Y(_032_)
  );
  \$_AND_  _146_ (
    .A(reg_pmc_ctrl[22]),
    .B(_047_),
    .Y(_033_)
  );
  \$_OR_  _147_ (
    .A(PADDR[0]),
    .B(PADDR[1]),
    .Y(_002_)
  );
  \$_AND_  _148_ (
    .A(reg_pmc_ctrl[23]),
    .B(_047_),
    .Y(_034_)
  );
  \$_AND_  _149_ (
    .A(reg_pmc_ctrl[24]),
    .B(_047_),
    .Y(_035_)
  );
  \$_AND_  _150_ (
    .A(reg_pmc_ctrl[25]),
    .B(_047_),
    .Y(_036_)
  );
  \$_AND_  _151_ (
    .A(reg_pmc_ctrl[26]),
    .B(_047_),
    .Y(_037_)
  );
  \$_AND_  _152_ (
    .A(reg_pmc_ctrl[27]),
    .B(_047_),
    .Y(_038_)
  );
  \$_AND_  _153_ (
    .A(reg_pmc_ctrl[28]),
    .B(_047_),
    .Y(_039_)
  );
  \$_AND_  _154_ (
    .A(reg_pmc_ctrl[29]),
    .B(_047_),
    .Y(_040_)
  );
  \$_AND_  _155_ (
    .A(reg_pmc_ctrl[30]),
    .B(_047_),
    .Y(_041_)
  );
  \$_OR_  _156_ (
    .A(_003_),
    .B(_002_),
    .Y(_004_)
  );
  \$_OR_  _157_ (
    .A(_006_),
    .B(_047_),
    .Y(_007_)
  );
  \$_OR_  _158_ (
    .A(_005_),
    .B(PADDR[3]),
    .Y(_045_)
  );
  \$_AND_  _159_ (
    .A(pmc_idle_out),
    .B(_056_),
    .Y(_011_)
  );
  \$_AND_  _160_ (
    .A(_056_),
    .B(cpu_pwr_sw_en),
    .Y(_015_)
  );
  \$_AND_  _161_ (
    .A(reg_pmc_ctrl[31]),
    .B(_047_),
    .Y(_048_)
  );
  \$_OR_  _162_ (
    .A(_010_),
    .B(_048_),
    .Y(_049_)
  );
  \$_AND_  _163_ (
    .A(_043_),
    .B(PSEL),
    .Y(_050_)
  );
  \$_AND_  _164_ (
    .A(_007_),
    .B(_050_),
    .Y(_051_)
  );
  \$_AND_  _165_ (
    .A(_049_),
    .B(_051_),
    .Y(PRDATA[31])
  );
  \$_AND_  _166_ (
    .A(reg_pmc_ctrl[0]),
    .B(_047_),
    .Y(_052_)
  );
  \$_OR_  _167_ (
    .A(_008_),
    .B(_052_),
    .Y(_053_)
  );
  \$_AND_  _168_ (
    .A(_051_),
    .B(_053_),
    .Y(PRDATA[0])
  );
  \$_OR_  _169_ (
    .A(PADDR[2]),
    .B(_045_),
    .Y(_046_)
  );
  \$_AND_  _170_ (
    .A(_000_[2]),
    .B(_050_),
    .Y(PRDATA[2])
  );
  \$_AND_  _171_ (
    .A(_000_[1]),
    .B(_050_),
    .Y(PRDATA[1])
  );
  \$_AND_  _172_ (
    .A(reg_pmc_ctrl[4]),
    .B(_047_),
    .Y(_054_)
  );
  \$_OR_  _173_ (
    .A(_009_),
    .B(_054_),
    .Y(_055_)
  );
  \$_AND_  _174_ (
    .A(_051_),
    .B(_055_),
    .Y(PRDATA[4])
  );
  \$_AND_  _175_ (
    .A(_000_[3]),
    .B(_050_),
    .Y(PRDATA[3])
  );
  \$_AND_  _176_ (
    .A(_000_[6]),
    .B(_050_),
    .Y(PRDATA[6])
  );
  \$_AND_  _177_ (
    .A(_000_[5]),
    .B(_050_),
    .Y(PRDATA[5])
  );
  \$_AND_  _178_ (
    .A(_000_[8]),
    .B(_050_),
    .Y(PRDATA[8])
  );
  \$_AND_  _179_ (
    .A(_000_[7]),
    .B(_050_),
    .Y(PRDATA[7])
  );
  \$_NOR_  _180_ (
    .A(_002_),
    .B(_046_),
    .Y(_047_)
  );
  \$_AND_  _181_ (
    .A(_000_[10]),
    .B(_050_),
    .Y(PRDATA[10])
  );
  \$_AND_  _182_ (
    .A(_000_[9]),
    .B(_050_),
    .Y(PRDATA[9])
  );
  \$_AND_  _183_ (
    .A(_000_[12]),
    .B(_050_),
    .Y(PRDATA[12])
  );
  \$_AND_  _184_ (
    .A(_000_[11]),
    .B(_050_),
    .Y(PRDATA[11])
  );
  \$_AND_  _185_ (
    .A(_000_[14]),
    .B(_050_),
    .Y(PRDATA[14])
  );
  \$_AND_  _186_ (
    .A(_000_[13]),
    .B(_050_),
    .Y(PRDATA[13])
  );
  \$_AND_  _187_ (
    .A(_000_[16]),
    .B(_050_),
    .Y(PRDATA[16])
  );
  \$_AND_  _188_ (
    .A(_000_[15]),
    .B(_050_),
    .Y(PRDATA[15])
  );
  \$_AND_  _189_ (
    .A(_000_[18]),
    .B(_050_),
    .Y(PRDATA[18])
  );
  \$_AND_  _190_ (
    .A(_000_[17]),
    .B(_050_),
    .Y(PRDATA[17])
  );
  \$_AND_  _191_ (
    .A(_042_),
    .B(_047_),
    .Y(_001_)
  );
  \$_AND_  _192_ (
    .A(_000_[20]),
    .B(_050_),
    .Y(PRDATA[20])
  );
  \$_AND_  _193_ (
    .A(_000_[19]),
    .B(_050_),
    .Y(PRDATA[19])
  );
  \$_AND_  _194_ (
    .A(_000_[22]),
    .B(_050_),
    .Y(PRDATA[22])
  );
  \$_AND_  _195_ (
    .A(_000_[21]),
    .B(_050_),
    .Y(PRDATA[21])
  );
  \$_AND_  _196_ (
    .A(_000_[24]),
    .B(_050_),
    .Y(PRDATA[24])
  );
  \$_AND_  _197_ (
    .A(_000_[23]),
    .B(_050_),
    .Y(PRDATA[23])
  );
  \$_AND_  _198_ (
    .A(_000_[26]),
    .B(_050_),
    .Y(PRDATA[26])
  );
  \$_AND_  _199_ (
    .A(_000_[25]),
    .B(_050_),
    .Y(PRDATA[25])
  );
  \$_AND_  _200_ (
    .A(_000_[28]),
    .B(_050_),
    .Y(PRDATA[28])
  );
  \$_AND_  _201_ (
    .A(_000_[27]),
    .B(_050_),
    .Y(PRDATA[27])
  );
  \$_OR_  _202_ (
    .A(hw_sleep_req),
    .B(reg_pmc_ctrl[0]),
    .Y(combined_sleep_req)
  );
  \$_AND_  _203_ (
    .A(_000_[30]),
    .B(_050_),
    .Y(PRDATA[30])
  );
  \$_AND_  _204_ (
    .A(_000_[29]),
    .B(_050_),
    .Y(PRDATA[29])
  );
  \$_AND_  _205_ (
    .A(reg_pmc_ctrl[1]),
    .B(_047_),
    .Y(_012_)
  );
  \$_NOT_  _206_ (
    .A(PADDR[3]),
    .Y(_058_)
  );
  \$_NOR_  _207_ (
    .A(PADDR[4]),
    .B(PADDR[5]),
    .Y(_059_)
  );
  \$_NOR_  _208_ (
    .A(_004_),
    .B(_005_),
    .Y(_056_)
  );
  \$_AND_  _209_ (
    .A(reg_pmc_timing[30]),
    .B(_063_),
    .Y(_122_)
  );
  \$_OR_  _210_ (
    .A(_041_),
    .B(_122_),
    .Y(_123_)
  );
  \$_AND_  _211_ (
    .A(_007_),
    .B(_123_),
    .Y(_000_[30])
  );
  \$_OR_  _212_ (
    .A(_063_),
    .B(_056_),
    .Y(_006_)
  );
  \$_AND_  _213_ (
    .A(reg_pmc_timing[4]),
    .B(_063_),
    .Y(_064_)
  );
  \$_OR_  _214_ (
    .A(_015_),
    .B(_064_),
    .Y(_009_)
  );
  \$_AND_  _215_ (
    .A(reg_pmc_timing[0]),
    .B(_063_),
    .Y(_065_)
  );
  \$_OR_  _216_ (
    .A(_011_),
    .B(_065_),
    .Y(_008_)
  );
  \$_AND_  _217_ (
    .A(reg_pmc_timing[1]),
    .B(_063_),
    .Y(_066_)
  );
  \$_OR_  _218_ (
    .A(_012_),
    .B(_066_),
    .Y(_067_)
  );
  \$_AND_  _219_ (
    .A(_007_),
    .B(_067_),
    .Y(_000_[1])
  );
  \$_AND_  _220_ (
    .A(reg_pmc_timing[2]),
    .B(_063_),
    .Y(_068_)
  );
  \$_NOR_  _221_ (
    .A(PADDR[6]),
    .B(PADDR[7]),
    .Y(_060_)
  );
  \$_OR_  _222_ (
    .A(_013_),
    .B(_068_),
    .Y(_069_)
  );
  \$_AND_  _223_ (
    .A(_007_),
    .B(_069_),
    .Y(_000_[2])
  );
  \$_AND_  _224_ (
    .A(reg_pmc_timing[3]),
    .B(_063_),
    .Y(_070_)
  );
  \$_OR_  _225_ (
    .A(_014_),
    .B(_070_),
    .Y(_071_)
  );
  \$_AND_  _226_ (
    .A(_007_),
    .B(_071_),
    .Y(_000_[3])
  );
  \$_AND_  _227_ (
    .A(reg_pmc_timing[5]),
    .B(_063_),
    .Y(_072_)
  );
  \$_OR_  _228_ (
    .A(_016_),
    .B(_072_),
    .Y(_073_)
  );
  \$_AND_  _229_ (
    .A(_007_),
    .B(_073_),
    .Y(_000_[5])
  );
  \$_AND_  _230_ (
    .A(reg_pmc_timing[6]),
    .B(_063_),
    .Y(_074_)
  );
  \$_OR_  _231_ (
    .A(_017_),
    .B(_074_),
    .Y(_075_)
  );
  \$_NAND_  _232_ (
    .A(_059_),
    .B(_060_),
    .Y(_005_)
  );
  \$_AND_  _233_ (
    .A(_007_),
    .B(_075_),
    .Y(_000_[6])
  );
  \$_AND_  _234_ (
    .A(reg_pmc_timing[7]),
    .B(_063_),
    .Y(_076_)
  );
  \$_OR_  _235_ (
    .A(_018_),
    .B(_076_),
    .Y(_077_)
  );
  \$_AND_  _236_ (
    .A(_007_),
    .B(_077_),
    .Y(_000_[7])
  );
  \$_AND_  _237_ (
    .A(reg_pmc_timing[8]),
    .B(_063_),
    .Y(_078_)
  );
  \$_OR_  _238_ (
    .A(_019_),
    .B(_078_),
    .Y(_079_)
  );
  \$_AND_  _239_ (
    .A(_007_),
    .B(_079_),
    .Y(_000_[8])
  );
  \$_AND_  _240_ (
    .A(reg_pmc_timing[9]),
    .B(_063_),
    .Y(_080_)
  );
  \$_OR_  _241_ (
    .A(_020_),
    .B(_080_),
    .Y(_081_)
  );
  \$_AND_  _242_ (
    .A(_007_),
    .B(_081_),
    .Y(_000_[9])
  );
  \$_NOR_  _243_ (
    .A(_002_),
    .B(PADDR[2]),
    .Y(_061_)
  );
  \$_AND_  _244_ (
    .A(reg_pmc_timing[10]),
    .B(_063_),
    .Y(_082_)
  );
  \$_OR_  _245_ (
    .A(_021_),
    .B(_082_),
    .Y(_083_)
  );
  \$_AND_  _246_ (
    .A(_007_),
    .B(_083_),
    .Y(_000_[10])
  );
  \$_AND_  _247_ (
    .A(reg_pmc_timing[11]),
    .B(_063_),
    .Y(_084_)
  );
  \$_OR_  _248_ (
    .A(_022_),
    .B(_084_),
    .Y(_085_)
  );
  \$_AND_  _249_ (
    .A(_007_),
    .B(_085_),
    .Y(_000_[11])
  );
  \$_AND_  _250_ (
    .A(reg_pmc_timing[12]),
    .B(_063_),
    .Y(_086_)
  );
  \$_OR_  _251_ (
    .A(_023_),
    .B(_086_),
    .Y(_087_)
  );
  \$_AND_  _252_ (
    .A(_007_),
    .B(_087_),
    .Y(_000_[12])
  );
  \$_AND_  _253_ (
    .A(reg_pmc_timing[13]),
    .B(_063_),
    .Y(_088_)
  );
  \$_NAND_  _254_ (
    .A(PADDR[3]),
    .B(_061_),
    .Y(_062_)
  );
  \$_OR_  _255_ (
    .A(_024_),
    .B(_088_),
    .Y(_089_)
  );
  \$_AND_  _256_ (
    .A(_007_),
    .B(_089_),
    .Y(_000_[13])
  );
  \$_AND_  _257_ (
    .A(reg_pmc_timing[14]),
    .B(_063_),
    .Y(_090_)
  );
  \$_OR_  _258_ (
    .A(_025_),
    .B(_090_),
    .Y(_091_)
  );
  \$_AND_  _259_ (
    .A(_007_),
    .B(_091_),
    .Y(_000_[14])
  );
  \$_AND_  _260_ (
    .A(reg_pmc_timing[15]),
    .B(_063_),
    .Y(_092_)
  );
  \$_OR_  _261_ (
    .A(_026_),
    .B(_092_),
    .Y(_093_)
  );
  \$_AND_  _262_ (
    .A(_007_),
    .B(_093_),
    .Y(_000_[15])
  );
  \$_AND_  _263_ (
    .A(reg_pmc_timing[16]),
    .B(_063_),
    .Y(_094_)
  );
  \$_OR_  _264_ (
    .A(_027_),
    .B(_094_),
    .Y(_095_)
  );
  \$_NOR_  _265_ (
    .A(_005_),
    .B(_062_),
    .Y(_063_)
  );
  \$_AND_  _266_ (
    .A(_007_),
    .B(_095_),
    .Y(_000_[16])
  );
  \$_AND_  _267_ (
    .A(reg_pmc_timing[17]),
    .B(_063_),
    .Y(_096_)
  );
  \$_OR_  _268_ (
    .A(_028_),
    .B(_096_),
    .Y(_097_)
  );
  \$_AND_  _269_ (
    .A(_007_),
    .B(_097_),
    .Y(_000_[17])
  );
  \$_AND_  _270_ (
    .A(reg_pmc_timing[18]),
    .B(_063_),
    .Y(_098_)
  );
  \$_OR_  _271_ (
    .A(_029_),
    .B(_098_),
    .Y(_099_)
  );
  \$_AND_  _272_ (
    .A(_007_),
    .B(_099_),
    .Y(_000_[18])
  );
  \$_AND_  _273_ (
    .A(reg_pmc_timing[19]),
    .B(_063_),
    .Y(_100_)
  );
  \$_OR_  _274_ (
    .A(_030_),
    .B(_100_),
    .Y(_101_)
  );
  \$_AND_  _275_ (
    .A(_007_),
    .B(_101_),
    .Y(_000_[19])
  );
  \$_AND_  _276_ (
    .A(_042_),
    .B(_063_),
    .Y(_057_)
  );
  \$_AND_  _277_ (
    .A(reg_pmc_timing[20]),
    .B(_063_),
    .Y(_102_)
  );
  \$_OR_  _278_ (
    .A(_031_),
    .B(_102_),
    .Y(_103_)
  );
  \$_AND_  _279_ (
    .A(_007_),
    .B(_103_),
    .Y(_000_[20])
  );
  \$_AND_  _280_ (
    .A(reg_pmc_timing[21]),
    .B(_063_),
    .Y(_104_)
  );
  \$_OR_  _281_ (
    .A(_032_),
    .B(_104_),
    .Y(_105_)
  );
  \$_AND_  _282_ (
    .A(_007_),
    .B(_105_),
    .Y(_000_[21])
  );
  \$_AND_  _283_ (
    .A(reg_pmc_timing[22]),
    .B(_063_),
    .Y(_106_)
  );
  \$_OR_  _284_ (
    .A(_033_),
    .B(_106_),
    .Y(_107_)
  );
  \$_AND_  _285_ (
    .A(_007_),
    .B(_107_),
    .Y(_000_[22])
  );
  \$_AND_  _286_ (
    .A(reg_pmc_timing[23]),
    .B(_063_),
    .Y(_108_)
  );
  \$_AND_  _287_ (
    .A(reg_pmc_timing[31]),
    .B(_063_),
    .Y(_010_)
  );
  \$_OR_  _288_ (
    .A(_034_),
    .B(_108_),
    .Y(_109_)
  );
  \$_AND_  _289_ (
    .A(_007_),
    .B(_109_),
    .Y(_000_[23])
  );
  \$_AND_  _290_ (
    .A(reg_pmc_timing[24]),
    .B(_063_),
    .Y(_110_)
  );
  \$_OR_  _291_ (
    .A(_035_),
    .B(_110_),
    .Y(_111_)
  );
  \$_AND_  _292_ (
    .A(_007_),
    .B(_111_),
    .Y(_000_[24])
  );
  \$_AND_  _293_ (
    .A(reg_pmc_timing[25]),
    .B(_063_),
    .Y(_112_)
  );
  \$_OR_  _294_ (
    .A(_036_),
    .B(_112_),
    .Y(_113_)
  );
  \$_AND_  _295_ (
    .A(_007_),
    .B(_113_),
    .Y(_000_[25])
  );
  \$_AND_  _296_ (
    .A(reg_pmc_timing[26]),
    .B(_063_),
    .Y(_114_)
  );
  \$_OR_  _297_ (
    .A(_037_),
    .B(_114_),
    .Y(_115_)
  );
  \$_NAND_  _298_ (
    .A(PADDR[2]),
    .B(_058_),
    .Y(_003_)
  );
  \$_AND_  _299_ (
    .A(_007_),
    .B(_115_),
    .Y(_000_[26])
  );
  \$_AND_  _300_ (
    .A(reg_pmc_timing[27]),
    .B(_063_),
    .Y(_116_)
  );
  \$_OR_  _301_ (
    .A(_038_),
    .B(_116_),
    .Y(_117_)
  );
  \$_AND_  _302_ (
    .A(_007_),
    .B(_117_),
    .Y(_000_[27])
  );
  \$_AND_  _303_ (
    .A(reg_pmc_timing[28]),
    .B(_063_),
    .Y(_118_)
  );
  \$_OR_  _304_ (
    .A(_039_),
    .B(_118_),
    .Y(_119_)
  );
  \$_AND_  _305_ (
    .A(_007_),
    .B(_119_),
    .Y(_000_[28])
  );
  \$_AND_  _306_ (
    .A(reg_pmc_timing[29]),
    .B(_063_),
    .Y(_120_)
  );
  \$_OR_  _307_ (
    .A(_040_),
    .B(_120_),
    .Y(_121_)
  );
  \$_AND_  _308_ (
    .A(_007_),
    .B(_121_),
    .Y(_000_[29])
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[0]  /* _309_ */ (
    .C(PCLK),
    .D(PWDATA[0]),
    .E(_001_),
    .Q(reg_pmc_ctrl[0]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[1]  /* _310_ */ (
    .C(PCLK),
    .D(PWDATA[1]),
    .E(_001_),
    .Q(reg_pmc_ctrl[1]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[2]  /* _311_ */ (
    .C(PCLK),
    .D(PWDATA[2]),
    .E(_001_),
    .Q(reg_pmc_ctrl[2]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[3]  /* _312_ */ (
    .C(PCLK),
    .D(PWDATA[3]),
    .E(_001_),
    .Q(reg_pmc_ctrl[3]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[4]  /* _313_ */ (
    .C(PCLK),
    .D(PWDATA[4]),
    .E(_001_),
    .Q(reg_pmc_ctrl[4]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[5]  /* _314_ */ (
    .C(PCLK),
    .D(PWDATA[5]),
    .E(_001_),
    .Q(reg_pmc_ctrl[5]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[6]  /* _315_ */ (
    .C(PCLK),
    .D(PWDATA[6]),
    .E(_001_),
    .Q(reg_pmc_ctrl[6]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[7]  /* _316_ */ (
    .C(PCLK),
    .D(PWDATA[7]),
    .E(_001_),
    .Q(reg_pmc_ctrl[7]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[8]  /* _317_ */ (
    .C(PCLK),
    .D(PWDATA[8]),
    .E(_001_),
    .Q(reg_pmc_ctrl[8]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[9]  /* _318_ */ (
    .C(PCLK),
    .D(PWDATA[9]),
    .E(_001_),
    .Q(reg_pmc_ctrl[9]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[10]  /* _319_ */ (
    .C(PCLK),
    .D(PWDATA[10]),
    .E(_001_),
    .Q(reg_pmc_ctrl[10]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[11]  /* _320_ */ (
    .C(PCLK),
    .D(PWDATA[11]),
    .E(_001_),
    .Q(reg_pmc_ctrl[11]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[12]  /* _321_ */ (
    .C(PCLK),
    .D(PWDATA[12]),
    .E(_001_),
    .Q(reg_pmc_ctrl[12]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[13]  /* _322_ */ (
    .C(PCLK),
    .D(PWDATA[13]),
    .E(_001_),
    .Q(reg_pmc_ctrl[13]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[14]  /* _323_ */ (
    .C(PCLK),
    .D(PWDATA[14]),
    .E(_001_),
    .Q(reg_pmc_ctrl[14]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[15]  /* _324_ */ (
    .C(PCLK),
    .D(PWDATA[15]),
    .E(_001_),
    .Q(reg_pmc_ctrl[15]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[16]  /* _325_ */ (
    .C(PCLK),
    .D(PWDATA[16]),
    .E(_001_),
    .Q(reg_pmc_ctrl[16]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[17]  /* _326_ */ (
    .C(PCLK),
    .D(PWDATA[17]),
    .E(_001_),
    .Q(reg_pmc_ctrl[17]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[18]  /* _327_ */ (
    .C(PCLK),
    .D(PWDATA[18]),
    .E(_001_),
    .Q(reg_pmc_ctrl[18]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[19]  /* _328_ */ (
    .C(PCLK),
    .D(PWDATA[19]),
    .E(_001_),
    .Q(reg_pmc_ctrl[19]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[20]  /* _329_ */ (
    .C(PCLK),
    .D(PWDATA[20]),
    .E(_001_),
    .Q(reg_pmc_ctrl[20]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[21]  /* _330_ */ (
    .C(PCLK),
    .D(PWDATA[21]),
    .E(_001_),
    .Q(reg_pmc_ctrl[21]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[22]  /* _331_ */ (
    .C(PCLK),
    .D(PWDATA[22]),
    .E(_001_),
    .Q(reg_pmc_ctrl[22]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[23]  /* _332_ */ (
    .C(PCLK),
    .D(PWDATA[23]),
    .E(_001_),
    .Q(reg_pmc_ctrl[23]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[24]  /* _333_ */ (
    .C(PCLK),
    .D(PWDATA[24]),
    .E(_001_),
    .Q(reg_pmc_ctrl[24]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[25]  /* _334_ */ (
    .C(PCLK),
    .D(PWDATA[25]),
    .E(_001_),
    .Q(reg_pmc_ctrl[25]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[26]  /* _335_ */ (
    .C(PCLK),
    .D(PWDATA[26]),
    .E(_001_),
    .Q(reg_pmc_ctrl[26]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[27]  /* _336_ */ (
    .C(PCLK),
    .D(PWDATA[27]),
    .E(_001_),
    .Q(reg_pmc_ctrl[27]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[28]  /* _337_ */ (
    .C(PCLK),
    .D(PWDATA[28]),
    .E(_001_),
    .Q(reg_pmc_ctrl[28]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[29]  /* _338_ */ (
    .C(PCLK),
    .D(PWDATA[29]),
    .E(_001_),
    .Q(reg_pmc_ctrl[29]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[30]  /* _339_ */ (
    .C(PCLK),
    .D(PWDATA[30]),
    .E(_001_),
    .Q(reg_pmc_ctrl[30]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_ctrl_reg[31]  /* _340_ */ (
    .C(PCLK),
    .D(PWDATA[31]),
    .E(_001_),
    .Q(reg_pmc_ctrl[31]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[0]  /* _341_ */ (
    .C(PCLK),
    .D(PWDATA[0]),
    .E(_057_),
    .Q(reg_pmc_timing[0]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[1]  /* _342_ */ (
    .C(PCLK),
    .D(PWDATA[1]),
    .E(_057_),
    .Q(reg_pmc_timing[1]),
    .R(PRESETn)
  );
  \$_DFFE_PN1P_  \reg_pmc_timing_reg[2]  /* _343_ */ (
    .C(PCLK),
    .D(PWDATA[2]),
    .E(_057_),
    .Q(reg_pmc_timing[2]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[3]  /* _344_ */ (
    .C(PCLK),
    .D(PWDATA[3]),
    .E(_057_),
    .Q(reg_pmc_timing[3]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[4]  /* _345_ */ (
    .C(PCLK),
    .D(PWDATA[4]),
    .E(_057_),
    .Q(reg_pmc_timing[4]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[5]  /* _346_ */ (
    .C(PCLK),
    .D(PWDATA[5]),
    .E(_057_),
    .Q(reg_pmc_timing[5]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[6]  /* _347_ */ (
    .C(PCLK),
    .D(PWDATA[6]),
    .E(_057_),
    .Q(reg_pmc_timing[6]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[7]  /* _348_ */ (
    .C(PCLK),
    .D(PWDATA[7]),
    .E(_057_),
    .Q(reg_pmc_timing[7]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[8]  /* _349_ */ (
    .C(PCLK),
    .D(PWDATA[8]),
    .E(_057_),
    .Q(reg_pmc_timing[8]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[9]  /* _350_ */ (
    .C(PCLK),
    .D(PWDATA[9]),
    .E(_057_),
    .Q(reg_pmc_timing[9]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[10]  /* _351_ */ (
    .C(PCLK),
    .D(PWDATA[10]),
    .E(_057_),
    .Q(reg_pmc_timing[10]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[11]  /* _352_ */ (
    .C(PCLK),
    .D(PWDATA[11]),
    .E(_057_),
    .Q(reg_pmc_timing[11]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[12]  /* _353_ */ (
    .C(PCLK),
    .D(PWDATA[12]),
    .E(_057_),
    .Q(reg_pmc_timing[12]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[13]  /* _354_ */ (
    .C(PCLK),
    .D(PWDATA[13]),
    .E(_057_),
    .Q(reg_pmc_timing[13]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[14]  /* _355_ */ (
    .C(PCLK),
    .D(PWDATA[14]),
    .E(_057_),
    .Q(reg_pmc_timing[14]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[15]  /* _356_ */ (
    .C(PCLK),
    .D(PWDATA[15]),
    .E(_057_),
    .Q(reg_pmc_timing[15]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[16]  /* _357_ */ (
    .C(PCLK),
    .D(PWDATA[16]),
    .E(_057_),
    .Q(reg_pmc_timing[16]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[17]  /* _358_ */ (
    .C(PCLK),
    .D(PWDATA[17]),
    .E(_057_),
    .Q(reg_pmc_timing[17]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[18]  /* _359_ */ (
    .C(PCLK),
    .D(PWDATA[18]),
    .E(_057_),
    .Q(reg_pmc_timing[18]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[19]  /* _360_ */ (
    .C(PCLK),
    .D(PWDATA[19]),
    .E(_057_),
    .Q(reg_pmc_timing[19]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[20]  /* _361_ */ (
    .C(PCLK),
    .D(PWDATA[20]),
    .E(_057_),
    .Q(reg_pmc_timing[20]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[21]  /* _362_ */ (
    .C(PCLK),
    .D(PWDATA[21]),
    .E(_057_),
    .Q(reg_pmc_timing[21]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[22]  /* _363_ */ (
    .C(PCLK),
    .D(PWDATA[22]),
    .E(_057_),
    .Q(reg_pmc_timing[22]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[23]  /* _364_ */ (
    .C(PCLK),
    .D(PWDATA[23]),
    .E(_057_),
    .Q(reg_pmc_timing[23]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[24]  /* _365_ */ (
    .C(PCLK),
    .D(PWDATA[24]),
    .E(_057_),
    .Q(reg_pmc_timing[24]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[25]  /* _366_ */ (
    .C(PCLK),
    .D(PWDATA[25]),
    .E(_057_),
    .Q(reg_pmc_timing[25]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[26]  /* _367_ */ (
    .C(PCLK),
    .D(PWDATA[26]),
    .E(_057_),
    .Q(reg_pmc_timing[26]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[27]  /* _368_ */ (
    .C(PCLK),
    .D(PWDATA[27]),
    .E(_057_),
    .Q(reg_pmc_timing[27]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[28]  /* _369_ */ (
    .C(PCLK),
    .D(PWDATA[28]),
    .E(_057_),
    .Q(reg_pmc_timing[28]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[29]  /* _370_ */ (
    .C(PCLK),
    .D(PWDATA[29]),
    .E(_057_),
    .Q(reg_pmc_timing[29]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[30]  /* _371_ */ (
    .C(PCLK),
    .D(PWDATA[30]),
    .E(_057_),
    .Q(reg_pmc_timing[30]),
    .R(PRESETn)
  );
  \$_DFFE_PN0P_  \reg_pmc_timing_reg[31]  /* _372_ */ (
    .C(PCLK),
    .D(PWDATA[31]),
    .E(_057_),
    .Q(reg_pmc_timing[31]),
    .R(PRESETn)
  );
  pmc_core u_pmc_core (
    .clk_aon(PCLK),
    .cpu_iso_en(cpu_iso_en),
    .cpu_pwr_sw_en(cpu_pwr_sw_en),
    .cpu_ret_restore(cpu_ret_restore),
    .cpu_ret_save(cpu_ret_save),
    .cpu_rst_n(cpu_rst_n),
    .pmc_idle(pmc_idle_out),
    .rst_n_aon(PRESETn),
    .sleep_req(combined_sleep_req),
    .wake_irq(wake_irq)
  );
  assign PREADY = 1'h1;
endmodule

module pmc_core(clk_aon, rst_n_aon, sleep_req, wake_irq, pmc_idle, cpu_ret_save, cpu_ret_restore, cpu_iso_en, cpu_rst_n, cpu_pwr_sw_en);
  input clk_aon;
  wire clk_aon;
  input rst_n_aon;
  wire rst_n_aon;
  input sleep_req;
  wire sleep_req;
  input wake_irq;
  wire wake_irq;
  output pmc_idle;
  wire pmc_idle;
  output cpu_ret_save;
  wire cpu_ret_save;
  output cpu_ret_restore;
  wire cpu_ret_restore;
  output cpu_iso_en;
  wire cpu_iso_en;
  output cpu_rst_n;
  wire cpu_rst_n;
  output cpu_pwr_sw_en;
  wire cpu_pwr_sw_en;
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire [3:0] current_state;
  wire [3:0] next_state;
  wire [3:0] timer;
  \$_NOT_  _066_ (
    .A(current_state[3]),
    .Y(_006_)
  );
  \$_NOT_  _067_ (
    .A(current_state[0]),
    .Y(_007_)
  );
  \$_AND_  _068_ (
    .A(_008_),
    .B(_015_),
    .Y(_016_)
  );
  \$_NAND_  _069_ (
    .A(current_state[3]),
    .B(_010_),
    .Y(_017_)
  );
  \$_MUX_  _070_ (
    .A(_010_),
    .B(_013_),
    .S(_006_),
    .Y(_018_)
  );
  \$_NOR_  _071_ (
    .A(_016_),
    .B(_018_),
    .Y(_019_)
  );
  \$_OR_  _072_ (
    .A(_001_),
    .B(_019_),
    .Y(_020_)
  );
  \$_NAND_  _073_ (
    .A(current_state[1]),
    .B(_015_),
    .Y(cpu_pwr_sw_en)
  );
  \$_OR_  _074_ (
    .A(_007_),
    .B(cpu_pwr_sw_en),
    .Y(_002_)
  );
  \$_NOT_  _075_ (
    .A(_002_),
    .Y(pmc_idle)
  );
  \$_OR_  _076_ (
    .A(wake_irq),
    .B(_002_),
    .Y(_021_)
  );
  \$_NOR_  _077_ (
    .A(current_state[3]),
    .B(current_state[2]),
    .Y(_022_)
  );
  \$_NOT_  _078_ (
    .A(current_state[1]),
    .Y(_008_)
  );
  \$_AND_  _079_ (
    .A(_010_),
    .B(_022_),
    .Y(_043_)
  );
  \$_NAND_  _080_ (
    .A(_009_),
    .B(_043_),
    .Y(_023_)
  );
  \$_AND_  _081_ (
    .A(_020_),
    .B(_023_),
    .Y(_024_)
  );
  \$_AND_  _082_ (
    .A(_021_),
    .B(_024_),
    .Y(_003_)
  );
  \$_NAND_  _083_ (
    .A(current_state[2]),
    .B(_010_),
    .Y(_025_)
  );
  \$_NOR_  _084_ (
    .A(_005_),
    .B(_025_),
    .Y(next_state[3])
  );
  \$_NOR_  _085_ (
    .A(_006_),
    .B(_025_),
    .Y(cpu_ret_restore)
  );
  \$_AND_  _086_ (
    .A(current_state[0]),
    .B(_008_),
    .Y(_026_)
  );
  \$_AND_  _087_ (
    .A(_022_),
    .B(_026_),
    .Y(cpu_ret_save)
  );
  \$_NAND_  _088_ (
    .A(_008_),
    .B(_012_),
    .Y(_027_)
  );
  \$_NOT_  _089_ (
    .A(sleep_req),
    .Y(_009_)
  );
  \$_AND_  _090_ (
    .A(_006_),
    .B(_027_),
    .Y(cpu_iso_en)
  );
  \$_NAND_  _091_ (
    .A(current_state[3]),
    .B(_011_),
    .Y(_028_)
  );
  \$_AND_  _092_ (
    .A(_007_),
    .B(current_state[1]),
    .Y(_029_)
  );
  \$_OR_  _093_ (
    .A(current_state[2]),
    .B(_029_),
    .Y(_030_)
  );
  \$_NAND_  _094_ (
    .A(_028_),
    .B(_030_),
    .Y(cpu_rst_n)
  );
  \$_AND_  _095_ (
    .A(_015_),
    .B(_029_),
    .Y(_041_)
  );
  \$_NOR_  _096_ (
    .A(cpu_ret_save),
    .B(_041_),
    .Y(_031_)
  );
  \$_OR_  _097_ (
    .A(_005_),
    .B(_031_),
    .Y(_032_)
  );
  \$_NAND_  _098_ (
    .A(wake_irq),
    .B(_040_),
    .Y(_033_)
  );
  \$_NAND_  _099_ (
    .A(sleep_req),
    .B(_043_),
    .Y(_034_)
  );
  \$_NOR_  _100_ (
    .A(current_state[0]),
    .B(current_state[1]),
    .Y(_010_)
  );
  \$_AND_  _101_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  \$_NAND_  _102_ (
    .A(_032_),
    .B(_035_),
    .Y(next_state[0])
  );
  \$_NOR_  _103_ (
    .A(_005_),
    .B(_014_),
    .Y(next_state[1])
  );
  \$_NOR_  _104_ (
    .A(current_state[3]),
    .B(_005_),
    .Y(_036_)
  );
  \$_MUX_  _105_ (
    .A(current_state[2]),
    .B(_007_),
    .S(current_state[1]),
    .Y(_037_)
  );
  \$_NAND_  _106_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  \$_NAND_  _107_ (
    .A(_033_),
    .B(_038_),
    .Y(next_state[2])
  );
  \$_AND_  _108_ (
    .A(current_state[1]),
    .B(_022_),
    .Y(_004_)
  );
  \$_NOR_  _109_ (
    .A(current_state[2]),
    .B(_017_),
    .Y(_044_)
  );
  \$_NOR_  _110_ (
    .A(current_state[3]),
    .B(_025_),
    .Y(_046_)
  );
  \$_OR_  _111_ (
    .A(current_state[0]),
    .B(current_state[1]),
    .Y(_011_)
  );
  \$_AND_  _112_ (
    .A(_015_),
    .B(_026_),
    .Y(_039_)
  );
  \$_AND_  _113_ (
    .A(_022_),
    .B(_026_),
    .Y(_042_)
  );
  \$_NOR_  _114_ (
    .A(_006_),
    .B(_025_),
    .Y(_045_)
  );
  \$_NAND_  _115_ (
    .A(current_state[2]),
    .B(current_state[0]),
    .Y(_012_)
  );
  \$_AND_  _116_ (
    .A(_011_),
    .B(_012_),
    .Y(_013_)
  );
  \$_NAND_  _117_ (
    .A(_006_),
    .B(_013_),
    .Y(_014_)
  );
  \$_AND_  _118_ (
    .A(_006_),
    .B(current_state[2]),
    .Y(_015_)
  );
  \$_NOT_  _119_ (
    .A(timer[0]),
    .Y(_047_)
  );
  \$_NOT_  _120_ (
    .A(_002_),
    .Y(_040_)
  );
  \$_AND_  _121_ (
    .A(_052_),
    .B(_053_),
    .Y(_054_)
  );
  \$_NAND_  _122_ (
    .A(_051_),
    .B(_054_),
    .Y(_055_)
  );
  \$_NAND_  _123_ (
    .A(_001_),
    .B(_055_),
    .Y(_056_)
  );
  \$_NAND_  _124_ (
    .A(_043_),
    .B(sleep_req),
    .Y(_057_)
  );
  \$_NAND_  _125_ (
    .A(wake_irq),
    .B(_040_),
    .Y(_058_)
  );
  \$_AND_  _126_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  \$_AND_  _127_ (
    .A(_056_),
    .B(_059_),
    .Y(_060_)
  );
  \$_AND_  _128_ (
    .A(timer[1]),
    .B(timer[0]),
    .Y(_061_)
  );
  \$_AND_  _129_ (
    .A(timer[2]),
    .B(_061_),
    .Y(_062_)
  );
  \$_XOR_  _130_ (
    .A(timer[3]),
    .B(_062_),
    .Y(_063_)
  );
  \$_NOR_  _131_ (
    .A(timer[1]),
    .B(timer[0]),
    .Y(_048_)
  );
  \$_AND_  _132_ (
    .A(_060_),
    .B(_063_),
    .Y(_000_[3])
  );
  \$_NOR_  _133_ (
    .A(_048_),
    .B(_061_),
    .Y(_064_)
  );
  \$_AND_  _134_ (
    .A(_060_),
    .B(_064_),
    .Y(_000_[1])
  );
  \$_AND_  _135_ (
    .A(_047_),
    .B(_060_),
    .Y(_000_[0])
  );
  \$_XOR_  _136_ (
    .A(timer[2]),
    .B(_061_),
    .Y(_065_)
  );
  \$_AND_  _137_ (
    .A(_060_),
    .B(_065_),
    .Y(_000_[2])
  );
  \$_NAND_  _138_ (
    .A(timer[2]),
    .B(_048_),
    .Y(_049_)
  );
  \$_NOR_  _139_ (
    .A(timer[3]),
    .B(_049_),
    .Y(_001_)
  );
  \$_NOT_  _140_ (
    .A(_001_),
    .Y(_005_)
  );
  \$_OR_  _141_ (
    .A(_046_),
    .B(_039_),
    .Y(_050_)
  );
  \$_NOR_  _142_ (
    .A(_041_),
    .B(_050_),
    .Y(_051_)
  );
  \$_NOR_  _143_ (
    .A(_004_),
    .B(_042_),
    .Y(_052_)
  );
  \$_NOR_  _144_ (
    .A(_044_),
    .B(_045_),
    .Y(_053_)
  );
  \$_DFFE_PN0P_  \current_state_reg[0]  /* _145_ */ (
    .C(clk_aon),
    .D(next_state[0]),
    .E(_003_),
    .Q(current_state[0]),
    .R(rst_n_aon)
  );
  \$_DFFE_PN0P_  \current_state_reg[1]  /* _146_ */ (
    .C(clk_aon),
    .D(next_state[1]),
    .E(_003_),
    .Q(current_state[1]),
    .R(rst_n_aon)
  );
  \$_DFFE_PN0P_  \current_state_reg[2]  /* _147_ */ (
    .C(clk_aon),
    .D(next_state[2]),
    .E(_003_),
    .Q(current_state[2]),
    .R(rst_n_aon)
  );
  \$_DFFE_PN0P_  \current_state_reg[3]  /* _148_ */ (
    .C(clk_aon),
    .D(next_state[3]),
    .E(_003_),
    .Q(current_state[3]),
    .R(rst_n_aon)
  );
  \$_DFF_PN0_  \timer_reg[0]  /* _149_ */ (
    .C(clk_aon),
    .D(_000_[0]),
    .Q(timer[0]),
    .R(rst_n_aon)
  );
  \$_DFF_PN0_  \timer_reg[1]  /* _150_ */ (
    .C(clk_aon),
    .D(_000_[1]),
    .Q(timer[1]),
    .R(rst_n_aon)
  );
  \$_DFF_PN0_  \timer_reg[2]  /* _151_ */ (
    .C(clk_aon),
    .D(_000_[2]),
    .Q(timer[2]),
    .R(rst_n_aon)
  );
  \$_DFF_PN0_  \timer_reg[3]  /* _152_ */ (
    .C(clk_aon),
    .D(_000_[3]),
    .Q(timer[3]),
    .R(rst_n_aon)
  );
endmodule
